name: clean_arch_bookly_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.15
  get: ^4.6.6
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GT-Sectra-Fine-Regular
      fonts:
        - asset: assets/fonts/GT-Sectra-Fine-Regular.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils/constants
  filename: app_images.dart
  field_prefix: null
  ignore_comments: true
  classname: AppImages
